version: '3'
services:

  childrescue_admin:
    image: docker.pkg.github.com/suite5/childrescue-frontend/childrescue-frontend:latest
    ports:
      - 8080:8080
    restart: unless-stopped
    container_name: childrescue_admin
