export default {
    facilityCases: [],
    cases: [],
    activeCases: [],
    facilityActiveCases: [],
    case: {},
    caseStructure: {
        organization: 1,
        child: null,
        facility: [],
        status: 'active',
        profile_photo: null,
        amber_alert: false,

        description: null,
        default_message: null,

        has_mobile_phone: false,
        has_money_or_credit: false,
        has_area_knowledge: false,
        clothing_with_scent: false,
        rescue_teams_utilized: false,
        volunteers_utilized: false,
        transit_country: null,
        disappearance_type: null,
        multi_times_case: null,
        probable_destinations: null,

        personal_data: {
            first_name: '',
            last_name: '',
            full_name: '',
            father_fullname: '',
            mother_fullname: '',
            phone: '',
        },
        demographic_data: {
            home_address: null,
            home_country: null,
            home_postal_code: null,
            home_city: null,
            birth_country: null,
            birth_city: null,
            education_level: null,
            languages_spoken: null,
            nationality: null,
            date_of_birth: null,
            gender: null,
            arrival_at_facility_date: null,
        },
        physical_data: {
            eye_color: '',
            hair_color: '',
            skin_color: null,
            height: null,
            weight: null,
            stature: null,
            body_type: null,
            characteristics: '',
        },
        medical_data: {
            medical_treatment_required: null,
            triggered_event: null,
            health_issues: null,
            health_issues_description: null,
        },
        psychological_data: {
            concerns: null,
            disappearance_reasons: null,
            personality: null,
            addiction: null,
            family: null,
            parents_profile: null,
            family_members: null,
            school_grades: null,
            school_absences: null,
            hobbies: null,
            relationship_status: null,
            religion: null,
        },
        social_media_data: {
            has_social_profiles: false,
            description: null,
        },
    },
};
