export default {
    feedbacks: null,
    feedback: {},
    feedbackStructure: {
        case: '',
        source: '',
        child_status: '',
        transportation: '',
        address: '',
        longitude: '',
        latitude: '',
        created_at: '',
        feedback_status: 'pending',
        feedback_image: '',
        checked_by_name: '',
        comment: '',
        date: '',
        time: '',
    },
};
